tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 104df9c9-f17e-42d2-9ca9-77aa97418c17 # Image - 1 Max
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 3fb32004-b270-4eef-b31e-b44d5e659e96
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: 5fa1a9f2-2e2b-41be-951e-54d3f20f5101
    userCondition: null
