field: c2ca9df1-28d9-4199-9640-1cbf54b91cd9 # Links - Max 4
fieldLayouts:
  486cd896-8cb3-4988-a0ac-f9dbce029fe6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f8c4b6c2-d2f3-4965-9ba8-3c96db57e372 # Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1388afd1-3c3c-477e-acd4-89a9cc1501b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13d9e3a6-c642-4ad7-88b5-487abe3f28f5 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2151fd0-11fb-42ee-bd1a-02bc5b8fd590
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08220778-a356-4556-80df-061637ce952b
        userCondition: null
fields:
  13d9e3a6-c642-4ad7-88b5-487abe3f28f5: # Label
    columnSuffix: tnjrbgah
    contentColumnType: string(200)
    fieldGroup: null
    handle: contentLabel
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: 50
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f8c4b6c2-d2f3-4965-9ba8-3c96db57e372: # Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: contentPage
    instructions: null
    name: Page
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Select page'
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: regular
name: Regular
sortOrder: 1
