childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  92169242-a6f4-4a70-838f-dca267c5a20d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 579019c4-1502-4d5e-abb7-4d7c04d47aa8 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6a30e96-811a-44e2-b3fd-662264ea8f04
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 116c32de-a55c-48d1-825a-4f3fc34ce15b
        userCondition: null
group: null
groupChildBlockTypes: true
handle: contact_simple_centered
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Contact Simple Centered'
sortOrder: 19
topLevel: true
