childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  179eaf73-ac40-4127-93c8-05396cc444b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6311f6e0-0362-4c66-bb2c-bd8cb7a04633 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd0365f8-309d-4578-95e8-7d2ef526d1be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2da3aa08-38e6-4b45-8c29-3f2ec6521952
        userCondition: null
group: null
groupChildBlockTypes: true
handle: content_body_two_max
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Body Paragraghs'
sortOrder: 2
topLevel: false
