childBlocks:
  - content_title_subtitle_svg
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  094ed4dd-b9f4-40d6-abf5-1bb7afb8110f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3628e283-b2cc-43b9-ac7e-c8d84e14200c # Plain Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab283d1c-85ce-4f66-b19d-7f3310f5155a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a4747f0-1b92-47bc-b3ed-433cc47edf6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6311f6e0-0362-4c66-bb2c-bd8cb7a04633 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0cab217-928f-4a34-8531-91b074a4fc5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 104df9c9-f17e-42d2-9ca9-77aa97418c17 # Image - 1 Max
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aab20d78-2875-44fa-805f-610bd10bb4b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ab1cd1c6-2327-4470-8f31-f9d2d57f7198
        userCondition: null
group: null
groupChildBlockTypes: true
handle: featured_with_image
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 3
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Feature with image'
sortOrder: 8
topLevel: true
