childBlocks:
  - content_title_subtitle_svg
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  10b78ab8-6cc7-47a0-b2e2-4fcfd3e57471:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3628e283-b2cc-43b9-ac7e-c8d84e14200c # Plain Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d435b2b4-9d1d-438e-a655-5c4692229836
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83dbe985-aac0-4594-9b73-5fe58caec687
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6311f6e0-0362-4c66-bb2c-bd8cb7a04633 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7621f35-fdfd-43a7-9919-189fc30a9522
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 104df9c9-f17e-42d2-9ca9-77aa97418c17 # Image - 1 Max
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da9f11a1-391e-48bd-b828-b607d41e0e80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7690bc79-8926-427e-aafa-900347d3989f
        userCondition: null
group: null
groupChildBlockTypes: true
handle: feature_grid_icons_with_large_image
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 6
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 3
minSiblingBlocks: 0
name: 'Feature Grid Icons With Large Image'
sortOrder: 10
topLevel: true
