childBlocks:
  - link_group
  - copyright_and_social
conditions: null
description: ''
enabled: true
field: 10b88df9-f053-420f-b8d5-5c61232d585f # Footer
fieldLayouts:
  fd4ae2fd-898c-42bb-9b46-9cd8a9374fca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c76c2b0-c215-4a85-bd3b-0cccffd7eb0a # Inline SVG
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cec0f4d7-0d5c-46bd-b5ae-f6cbc1f4cbf4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 579019c4-1502-4d5e-abb7-4d7c04d47aa8 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9262bd3e-4c13-4fc8-a1f0-d8ddff8f1fd7
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 218ac731-c3a2-42d6-9fb6-1f8306b5c4d0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff30f3d5-f748-4769-9e42-8a09f7497735
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3628e283-b2cc-43b9-ac7e-c8d84e14200c # Plain Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 048cdce6-e581-4d86-bdb3-9a69a1787c77
            userCondition: null
            warning: null
            width: 100
        name: 'Newsletter Info'
        uid: 3e540da9-8b57-4e22-8c98-2f1018116ad9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df7ff4dd-dc38-479e-b649-a8ef8a698d3f # Icon Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64e37615-3261-47b6-a4ae-b557eb7bc6e6
            userCondition: null
            warning: null
            width: 100
        name: Social
        uid: 78d673a0-dc42-4982-9e62-9aa4b4d7c380
        userCondition: null
group: null
groupChildBlockTypes: true
handle: footer_4_col_with_newsletter_below
icon: null
ignorePermissions: true
maxBlocks: 7
maxChildBlocks: 6
maxSiblingBlocks: 0
minBlocks: 1
minChildBlocks: 3
minSiblingBlocks: 0
name: '4 Column with Newsletter below'
sortOrder: 2
topLevel: true
