childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  a08b0c45-0f11-4d39-84ed-ad7d6593fb66:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9129b3f1-6b8a-4d90-a315-00edfd4fa622 # Subtitle Link Box
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec1da406-0786-4720-b844-03da2d1d08a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a4747f0-1b92-47bc-b3ed-433cc47edf6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6311f6e0-0362-4c66-bb2c-bd8cb7a04633 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0cab217-928f-4a34-8531-91b074a4fc5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87d02ee3-cd56-40a7-95bf-29a706064f6c # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45b609bb-a110-42ee-a04c-d2a5b126e02f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 104df9c9-f17e-42d2-9ca9-77aa97418c17 # Image - 1 Max
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 325d5354-1c46-4dc4-b2fb-5f2e3467e74c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 4653e5c2-8192-4e65-9a58-a477f1f894d5
        userCondition: null
group: null
groupChildBlockTypes: true
handle: hero_image_background
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Hero with Background Image'
sortOrder: 7
topLevel: true
