childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  2ce4eebd-b4a5-48d2-b581-97cb03f94b83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c76c2b0-c215-4a85-bd3b-0cccffd7eb0a # Inline SVG
            instructions: null
            label: Logo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4acfe4a3-0164-4170-be14-503203d2ba21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9129b3f1-6b8a-4d90-a315-00edfd4fa622 # Subtitle Link Box
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec1da406-0786-4720-b844-03da2d1d08a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a4747f0-1b92-47bc-b3ed-433cc47edf6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6311f6e0-0362-4c66-bb2c-bd8cb7a04633 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0cab217-928f-4a34-8531-91b074a4fc5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87d02ee3-cd56-40a7-95bf-29a706064f6c # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45b609bb-a110-42ee-a04c-d2a5b126e02f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 104df9c9-f17e-42d2-9ca9-77aa97418c17 # Image - 1 Max
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 325d5354-1c46-4dc4-b2fb-5f2e3467e74c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 5f437e30-b8fb-417f-be49-8a494a0b3eab
        userCondition: null
group: null
groupChildBlockTypes: true
handle: hero_split_with_image
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Hero Split with Image'
sortOrder: 6
topLevel: true
