childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  757ce033-d5ec-47b3-8dc0-ad5673ca7b48:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 24e1c6a2-59d3-46be-8ed1-6d3731715bd4 # Shopify Product ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6b542d4-010f-4e36-b645-cafd45679283
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2ca9df1-28d9-4199-9640-1cbf54b91cd9 # Links - Max 4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ac3ae6f-70c8-4953-b4bb-ecc5dc6aadbe
            userCondition: null
            warning: null
            width: 100
        name: Breadcrumbs
        uid: 300f2632-3242-4ace-bd01-161d262188e4
        userCondition: null
group: null
groupChildBlockTypes: true
handle: product_overview_with_multiple_style_changes
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Product Overview With Multiple Style Changes'
sortOrder: 21
topLevel: true
