childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  6726af44-8b5a-494f-876b-9d0565f6253a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f893851-015f-4f9c-b44b-dacd51e743ea
            userCondition: null
            warning: null
            width: 100
        name: Shopify
        uid: 7000c40f-3e82-4e85-bad2-a53c00b1ccf7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: product_overview_with_multiple_style_changes
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Product Overview With Multiple Style Changes'
sortOrder: 21
topLevel: true
