childBlocks:
  - content_title_subtitle_plain
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  50d51449-552d-4fe8-813c-4bd94d979eee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a5ecc83e-c8ee-4d47-ba2f-17bb67ee6fa9 # Plain Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3907947-2281-4e30-8dcf-d4992dbe3ef5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3628e283-b2cc-43b9-ac7e-c8d84e14200c # Plain Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9daccc7-f44c-44d0-add3-f4c840d8f85b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a78e6566-16a4-459d-b852-3f9e2ef076ff
        userCondition: null
group: null
groupChildBlockTypes: true
handle: stats_simple_grid
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 4
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 3
minSiblingBlocks: 0
name: 'Stats Simple Grid'
sortOrder: 13
topLevel: true
