fieldLayouts:
  d0c0ad20-e522-44e3-8e59-c15bc6fd36bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a942ae87-aa76-4daf-91e1-b5939c12e7df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4b93b3be-f7cf-45f9-8d70-bff72d550ac2 # Hero Optimization
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f3d5e90-17c6-4f0b-8466-1a5bd0a5a108
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8498d62-a4a7-4a2d-a853-cd2a074e1d77 # Default Optimization
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3060a0b-a832-4fc0-be2e-897f7d20351d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 590bc761-4626-4f4d-af72-18a2d192e427
        userCondition: null
fs: default
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: default
transformSubpath: ''
