columnSuffix: null
contentColumnType: string
fieldGroup: f1eb585f-5636-4ac4-84ee-0d7bbe197b4f # Content Builders
handle: builder_header
instructions: null
name: Header
searchable: false
settings:
  maxBlocks: 1
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
