columnSuffix: null
contentColumnType: string
fieldGroup: 8e54d255-9214-4889-8d34-f3ae16facab1 # Reusable Fields
handle: content_buttons
instructions: null
name: Buttons
searchable: false
settings:
  contentTable: '{{%matrixcontent_content_buttons}}'
  maxBlocks: 2
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
