columnSuffix: null
contentColumnType: string
fieldGroup: 8e54d255-9214-4889-8d34-f3ae16facab1 # Reusable Fields
handle: icon_links
instructions: null
name: 'Icon Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_icon_links}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
