columnSuffix: ckofwuks
contentColumnType: text
fieldGroup: 8e54d255-9214-4889-8d34-f3ae16facab1 # Reusable Fields
handle: lead_paragraph
instructions: null
name: 'Lead Paragraph'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
