columnSuffix: null
contentColumnType: string
fieldGroup: 8e54d255-9214-4889-8d34-f3ae16facab1 # Reusable Fields
handle: link_max_1
instructions: null
name: 'Link - Max 1'
searchable: false
settings:
  contentTable: '{{%matrixcontent_link_max_1}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
