columnSuffix: null
contentColumnType: string
fieldGroup: 8e54d255-9214-4889-8d34-f3ae16facab1 # Reusable Fields
handle: subtitle_box_pill
instructions: null
name: 'Subtitle Link Box'
searchable: false
settings:
  contentTable: '{{%matrixcontent_subtitle_box_pill}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
