defaultPlacement: end
enableVersioning: true
handle: globalContent
name: Globals
propagationMethod: all
siteSettings:
  abd4084c-0d61-4110-97b0-2f095d8c5445: # Chaos
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
